language: python
python:
  - "3.7"
cache: pip
install:
  # Reducing verbosity is needed because of Travis' limit on log length
  - pip install -e . --quiet
  - pip install pytest pytest-cov
jobs:
  include:
    - script: ./tests/end2end/run_exp1.sh
    - script: config/hooks/pre-commit
    - script: pytest

